name: cloudrun-deploy-webapp
on:
  push:
    branches:
      - main
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build & Publish
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT }}

      - name: Install dependencies
        run: cd website ; npm install; npm run build

      - name: Deploy website
        run: |
          gcloud run deploy dmvtest --source website --region us-central1 --allow-unauthenticated

      - name: Install dependencies
        run: cd webapp ; npm install

      - name: Deploy webapp
        run: |
          gcloud run deploy webapp --source webapp --region us-central1 --allow-unauthenticated
